customColorSchemes:
  - name: "*Tokyo Night"
    foreground: "#787c99"
    background: "#16161e"
    cursor: "#ffffff"
    colors:
      - "#363b54"
      - "#f7768e"
      - "#41a6b5"
      - "#e0af68"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#787c99"
      - "#363b54"
      - "#f7768e"
      - "#41a6b5"
      - "#e0af68"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#787c99"
    selection: "#ffffff"
