hotkeys:
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-line:
    - Ctrl-Shift-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  scroll-to-bottom:
    - Ctrl-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - Ctrl-Shift-T
  toggle-window:
    - Ctrl-Space
  new-window:
    - Ctrl-Shift-N
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-Z
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-S
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-E
  command-selector:
    - Ctrl-Shift-P
terminal:
  frontend: xterm-webgl
  fontWeight: 400
  fontWeightBold: 700
  fallbackFont: null
  linePadding: 1
  bell: 'off'
  bracketedPaste: true
  background: theme
  ligatures: true
  cursor: block
  cursorBlink: true
  hideTabIndex: false
  showTabProfileIcon: true
  hideCloseButton: false
  hideTabOptionsButton: false
  rightClick: clipboard
  pasteOnMiddleClick: false
  copyOnSelect: true
  copyAsHTML: true
  scrollOnInput: true
  altIsMeta: false
  wordSeparator: ' ()[]{}''"'
  colorScheme:
    name: Catppuccin Mocha Darker
    foreground: '#cdd6f4'
    background: hsl(240, 21%, 8%)
    selection: null
    cursor: '#f5e0dc'
    cursorAccent: null
    colors:
      - '#45475a'
      - '#f38ba8'
      - '#a6e3a1'
      - '#f9e2af'
      - '#89b4fa'
      - '#f5c2e7'
      - '#94e2d5'
      - '#bac2de'
      - '#585b70'
      - '#f38ba8'
      - '#a6e3a1'
      - '#f9e2af'
      - '#89b4fa'
      - '#f5c2e7'
      - '#94e2d5'
      - '#a6adc8'
  lightColorScheme:
    name: Catppuccin Mocha Darker
    foreground: '#cdd6f4'
    background: hsl(240, 21%, 8%)
    selection: null
    cursor: '#f5e0dc'
    cursorAccent: null
    colors:
      - '#45475a'
      - '#f38ba8'
      - '#a6e3a1'
      - '#f9e2af'
      - '#89b4fa'
      - '#f5c2e7'
      - '#94e2d5'
      - '#bac2de'
      - '#585b70'
      - '#f38ba8'
      - '#a6e3a1'
      - '#f9e2af'
      - '#89b4fa'
      - '#f5c2e7'
      - '#94e2d5'
      - '#a6adc8'
  customColorSchemes:
    - name: '*Tokyo Night'
      foreground: '#787c99'
      background: '#16161e'
      cursor: '#ffffff'
      colors:
        - '#363b54'
        - '#f7768e'
        - '#41a6b5'
        - '#e0af68'
        - '#7aa2f7'
        - '#bb9af7'
        - '#7dcfff'
        - '#787c99'
        - '#363b54'
        - '#f7768e'
        - '#41a6b5'
        - '#e0af68'
        - '#7aa2f7'
        - '#bb9af7'
        - '#7dcfff'
        - '#787c99'
      selection: '#ffffff'
    - name: '*Tokyo Night Bright'
      foreground: '#c0caf5'
      background: hsl(235, 19%, 8%)
      cursor: '#C0CAF5'
      colors:
        - '#15161E'
        - '#F7768E'
        - '#9ECE6A'
        - '#E0AF68'
        - '#7AA2F7'
        - '#BB9AF7'
        - '#7DCFFF'
        - '#A9B1D6'
        - '#15161E'
        - '#F7768E'
        - '#9ECE6A'
        - '#E0AF68'
        - '#7AA2F7'
        - '#BB9AF7'
        - '#7DCFFF'
        - '#A9B1D6'
    - name: Catppuccin Mocha
      foreground: '#cdd6f4'
      background: '#1e1e2e'
      selection: null
      cursor: '#f5e0dc'
      cursorAccent: null
      colors:
        - '#45475a'
        - '#f38ba8'
        - '#a6e3a1'
        - '#f9e2af'
        - '#89b4fa'
        - '#f5c2e7'
        - '#94e2d5'
        - '#bac2de'
        - '#585b70'
        - '#f38ba8'
        - '#a6e3a1'
        - '#f9e2af'
        - '#89b4fa'
        - '#f5c2e7'
        - '#94e2d5'
        - '#a6adc8'
    - name: Night Owl Darker
      foreground: '#d6deeb'
      background: hsl(207, 95%, 5%)
      cursor: '#80a4c2'
      colors:
        - '#011627'
        - '#ef5350'
        - '#22da6e'
        - '#addb67'
        - '#82aaff'
        - '#c792ea'
        - '#21c7a8'
        - '#ffffff'
        - '#969696'
        - '#ef5350'
        - '#22da6e'
        - '#ffeb95'
        - '#82aaff'
        - '#c792ea'
        - '#7fdbca'
        - '#ffffff'
    - name: '*Tokyo Night Darker'
      foreground: '#787c99'
      background: hsl(240, 15%, 8%)
      cursor: '#ffffff'
      colors:
        - '#363b54'
        - '#f7768e'
        - '#41a6b5'
        - '#e0af68'
        - '#7aa2f7'
        - '#bb9af7'
        - '#7dcfff'
        - '#787c99'
        - '#363b54'
        - '#f7768e'
        - '#41a6b5'
        - '#e0af68'
        - '#7aa2f7'
        - '#bb9af7'
        - '#7dcfff'
        - '#787c99'
      selection: '#ffffff'
    - name: Catppuccin Mocha Darker
      foreground: '#cdd6f4'
      background: hsl(240, 21%, 8%)
      selection: null
      cursor: '#f5e0dc'
      cursorAccent: null
      colors:
        - '#45475a'
        - '#f38ba8'
        - '#a6e3a1'
        - '#f9e2af'
        - '#89b4fa'
        - '#f5c2e7'
        - '#94e2d5'
        - '#bac2de'
        - '#585b70'
        - '#f38ba8'
        - '#a6e3a1'
        - '#f9e2af'
        - '#89b4fa'
        - '#f5c2e7'
        - '#94e2d5'
        - '#a6adc8'
  warnOnMultilinePaste: true
  searchRegexAlwaysEnabled: false
  searchOptions:
    regex: false
    wholeWord: false
    caseSensitive: false
  detectProgress: true
  scrollbackLines: 25000
  drawBoldTextInBrightColors: true
  sixel: true
  minimumContrastRatio: 4
  trimWhitespaceOnPaste: true
  font: MesloLGS Nerd Font
  autoOpen: false
  useConPTY: true
  environment: {}
  setComSpec: false
  profile: local:powershell
  showBuiltinProfiles: true
  showRecentProfiles: 3
  focusFollowsMouse: true
  identification: wt
ssh:
  warnOnClose: false
  winSCPPath: null
  agentType: auto
  agentPath: null
  x11Display: null
  knownHosts: []
  verifyHostKeys: true
configSync:
  configID: null
  auto: false
  parts:
    hotkeys: true
    appearance: true
    vault: true
clickableLinks:
  modifier: null
accessibility:
  animations: true
appearance:
  dock: 'off'
  dockScreen: current
  dockFill: 0.5
  dockSpace: 1
  dockHideOnBlur: false
  dockAlwaysOnTop: true
  tabsLocation: top
  tabsInFullscreen: false
  cycleTabs: true
  theme: Follow the color scheme
  css: |-
    split-tab>.child {
        position: absolute;
        transition: .125s all;
        opacity: 1; 
    }
  vibrancyType: blur
  lastTabClosesWindow: false
  colorSchemeMode: dark
  opacity: 1
  spaciness: 1.1
profiles: []
groups: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
recoverTabs: true
enableAnalytics: true
enableWelcomeTab: false
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAutomaticUpdates: true
version: 7
vault: null
encrypted: false
enableExperimentalFeatures: false
commandBlacklist: []
providerBlacklist: []
profileBlacklist: []
hacks:
  disableGPU: false
  disableVibrancyWhileDragging: false
  enableFluentBackground: false
language: null
defaultQuickConnectProvider: ssh
pluginBlacklist: []
